INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Primeiro Partido social', 'PPS', 'ESQUERDA', '1980-02-10');
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Segundo PArtido Nacional', 'SPN', 'DIREITA', '1990-12-20');
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('TerceiroPartido dos Trabalhadores', 'TPT', 'CENTRO', '1982-05-13');


INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('André Marinho', 'Presidente', '1967-01-30', 'MASCULINO');

INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('Maria Jośe', 'Governado', '1980-10-25', 'Feminino');

INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('Maria Nazaré', 'Deputado Federal', '1982-09-20', 'Feminino');

INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('Joana Darck', 'Prefeita', '1975-05-15', 'Feminino');
